import { corporateKitImage } from "@/lib/kitImageMap";
const normalizeImageTitle = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "");

const folderImage = (folder: string, file: string) => `/images/${folder}/${file}`;

const LOCAL_IMAGE_POOLS = {
  backpacks: [
    folderImage("Backpacks", "1.jpg"),
    folderImage("Backpacks", "2.jpg"),
    folderImage("Backpacks", "3.jpg"),
    folderImage("Backpacks", "4.jpg"),
    folderImage("Backpacks", "5.jpg"),
    folderImage("Backpacks", "6.jpg"),
  ],
  deskOrganiser: [
    folderImage("Desk Organsier", "1.jpg"),
    folderImage("Desk Organsier", "2.jpg"),
    folderImage("Desk Organsier", "3.jpg"),
    folderImage("Desk Organsier", "4.jpg"),
  ],
  diaries: [
    folderImage("Diaries", "1.jpg"),
    folderImage("Diaries", "2.jpg"),
    folderImage("Diaries", "3.jpg"),
    folderImage("Diaries", "4.jpg"),
    folderImage("Diaries", "5.jpg"),
    folderImage("Diaries", "6.jpg"),
    folderImage("Diaries", "7.jpg"),
    folderImage("Diaries", "8.jpg"),
  ],
  diwaliHampers: [
    folderImage("Diwali Hampers", "1.jpg"),
    folderImage("Diwali Hampers", "2.jpg"),
    folderImage("Diwali Hampers", "3.jpg"),
    folderImage("Diwali Hampers", "4.jpg"),
    folderImage("Diwali Hampers", "5.jpg"),
  ],
  duffleBags: [
    folderImage("Duffle Bags", "1.webp"),
    folderImage("Duffle Bags", "2.jpg"),
    folderImage("Duffle Bags", "3.jpg"),
    folderImage("Duffle Bags", "4.jpg"),
    folderImage("Duffle Bags", "5.webp"),
    folderImage("Duffle Bags", "6.webp"),
  ],
  eidHampers: [
    folderImage("EID HAmpers", "1.jpg"),
    folderImage("EID HAmpers", "2.jpg"),
    folderImage("EID HAmpers", "3.jpg"),
    folderImage("EID HAmpers", "4.jpg"),
    folderImage("EID HAmpers", "5.jpg"),
  ],
  festiveHampers: [
    folderImage("Festive Hampers", "1.jpg"),
    folderImage("Festive Hampers", "2.jpg"),
    folderImage("Festive Hampers", "3.jpg"),
  ],
  holiHampers: [
    folderImage("Holi Hampers", "4b4cafcfc2eac114bea36d257d45a580.jpg"),
  ],
  laptopBags: [
    folderImage("Laptop Bags", "1.png"),
    folderImage("Laptop Bags", "2.png"),
    folderImage("Laptop Bags", "3.png"),
    folderImage("Laptop Bags", "4.png"),
    folderImage("Laptop Bags", "5.jpg"),
  ],
  slingBags: [
    folderImage("slingbags", "classicslingbag.png"),
    folderImage("slingbags", "premiumslingbag.png"),
    folderImage("slingbags", "executiveslingbag.png"),
  ],
  roundNeckTshirts: [
    folderImage("roundnecktshirt", "classicroundnecktshirt.png"),
    folderImage("roundnecktshirt", "premiumroundnecktshirt.png"),
    folderImage("roundnecktshirt", "executiveroundnecktshirt.png"),
  ],
  sportsCaps: [
    folderImage("sportscap", "classicsportcap.png"),
    folderImage("sportscap", "premiumsportcap.png"),
    folderImage("sportscap", "executivesportcap.png"),
  ],
  cottonCaps: [
    folderImage("cottoncaps", "classiccottoncap.png"),
    folderImage("cottoncaps", "premiumcottoncap.png"),
    folderImage("cottoncaps", "executivecottoncap.png"),
    folderImage("cottoncaps", "ecocottoncap.png"),
  ],
  mousePad: [
    folderImage("Mouse pad", "General.jpg"),
    folderImage("Mouse pad", "1.jpg"),
    folderImage("Mouse pad", "2.jpg"),
    folderImage("Mouse pad", "3.jpg"),
  ],
  paperWeight: [
    folderImage("Paper Weight", "1.jpg"),
    folderImage("Paper Weight", "2.jpg"),
    folderImage("Paper Weight", "3.jpg"),
  ],
  tableMat: [
    folderImage("Table Mat", "1.jpg"),
    folderImage("Table Mat", "2.jpg"),
    folderImage("Table Mat", "3.jpg"),
    folderImage("Table Mat", "4.jpg"),
  ],
  trolleyBags: [
    folderImage("Trolley Bags", "1.jpg"),
    folderImage("Trolley Bags", "2.jpg"),
    folderImage("Trolley Bags", "3.jpg"),
    folderImage("Trolley Bags", "4.jpg"),
    folderImage("Trolley Bags", "5.jpg"),
  ],
};

const LOCAL_CATALOG_IMAGES_BY_TITLE: Record<string, string> = {
  [normalizeImageTitle("Executive Leather Desk Mat")]: LOCAL_IMAGE_POOLS.tableMat[0],
  [normalizeImageTitle("Solid Wood Wireless Charging Dock")]: "/images/wirelesscharging.png",
  [normalizeImageTitle("Smart Temperature LED Sipper")]: "/images/smartsipper.png",
  [normalizeImageTitle("Premium Aluminum Laptop Stand")]: "/images/laptopstand.png",
  [normalizeImageTitle("Metal Rotating Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Wireless Charging Mousepad")]: "/images/mousepad.png",
  [normalizeImageTitle("Custom Tabletop Calendar")]: "/images/tabletopup.png",
  [normalizeImageTitle("Executive Acrylic Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Classic Acrylic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Eco Acrylic Keychain")]: "/images/ecoacrylickeychain.png",
  [normalizeImageTitle("Premium Acrylic Keychain")]: "/images/premiummetalkeychain.png",
  [normalizeImageTitle("Eco Backpack")]: LOCAL_IMAGE_POOLS.backpacks[0],
  [normalizeImageTitle("Architect Kits 1")]: "/images/architectkit1.png",
  [normalizeImageTitle("Architect Kits 2")]: "/images/architectkits2.png",
  [normalizeImageTitle("Architect Kits 3")]: "/images/architectkits3.png",
  [normalizeImageTitle("Architect Kits 4")]: "/images/architectkits4.png",
  [normalizeImageTitle("Architect Kits 5")]: "/images/architectkits5.png",
  [normalizeImageTitle("Contractor Kits 1")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Contractor Kits 2")]: "/images/contractorkits2.png",
  [normalizeImageTitle("Contractor Kits 3")]: "/images/contractorkits3.png",
  [normalizeImageTitle("Contractor Kits 4")]: "/images/contractorkits4.png",
  [normalizeImageTitle("Contractor Kits 5")]: "/images/contractorkits5.png",
  [normalizeImageTitle("Premium Corporate T-Shirt")]: "/images/polotshirt.png",
  [normalizeImageTitle("Classic Corporate T-Shirt")]: "/images/classictimelesspolotshirt.png",
  [normalizeImageTitle("Eco Corporate T-Shirt")]: "/images/tshirtgreen.png",
  [normalizeImageTitle("Executive Corporate T-Shirt")]: "/images/tshirtblue.png",

  // T-Shirts
  [normalizeImageTitle("T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Polo T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],
  [normalizeImageTitle("Crew Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],
  [normalizeImageTitle("Dry Fit T-Shirts")]: "/images/tshirtblue.png",
  [normalizeImageTitle("Event T-Shirts")]: "/images/tshirtyellow.png",
  [normalizeImageTitle("Polo T-Shirt")]: "/images/polotshirt.png",
  [normalizeImageTitle("Cotton Crew Neck")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],
  [normalizeImageTitle("Corporate Dry Fit Tee")]: "/images/tshirtblue.png",
  [normalizeImageTitle("Premium Embroidered Tee")]: "/images/classictimelesspolotshirt.png",
  [normalizeImageTitle("Employee Event T-Shirt")]: "/images/tshirtyellow.png",
  [normalizeImageTitle("Printed Branding Tee")]: "/images/tshirtgreen.png",
  [normalizeImageTitle("Classic Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],
  [normalizeImageTitle("Premium Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[1],
  [normalizeImageTitle("Executive Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[2],
  [normalizeImageTitle("Eco Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],

  // Keychains
  [normalizeImageTitle("Keychains")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Metal Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Leather Keychain")]: "/images/leatherkeychain.png",
  [normalizeImageTitle("Acrylic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Plastic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Wooden Keychain")]: "/images/woodenkeychain.png",
  [normalizeImageTitle("Premium Metal Keychain")]: "/images/premiummetalkeychain.png",

  // Pens
  [normalizeImageTitle("Pens")]: "/images/pen1.png",
  [normalizeImageTitle("Premium Pens")]: "/images/pen1.png",
  [normalizeImageTitle("Eco Pens")]: "/images/pen2.png",
  [normalizeImageTitle("Gift Box Pens")]: "/images/pen3.png",
  [normalizeImageTitle("Engraved Pens")]: "/images/pen4.png",
  [normalizeImageTitle("Premium Pen Gift Set")]: "/images/pen5.png",
  [normalizeImageTitle("Parker Premium Pen")]: "/images/pen1.png",
  [normalizeImageTitle("Metal Roller Pen")]: "/images/pen2.png",
  [normalizeImageTitle("Bamboo Eco Pen")]: "/images/pen3.png",
  [normalizeImageTitle("Executive Signature Pen")]: "/images/pen4.png",
  [normalizeImageTitle("Stylus Pen")]: "/images/pen5.png",
  [normalizeImageTitle("Gift Box Pen Set")]: "/images/pen3.png",
  [normalizeImageTitle("Engraved Corporate Pen")]: "/images/pen4.png",
  [normalizeImageTitle("Premium Ball Pen")]: "/images/pen1.png",

  // Bottles & Drinkware
  [normalizeImageTitle("Drinkware")]: "/images/sportsbottle.png",
  [normalizeImageTitle("Flasks")]: "/images/flaskbottle.png",
  [normalizeImageTitle("Bottles")]: "/images/sportsbottle.png",
  [normalizeImageTitle("Vacuum Flask")]: "/images/premiumvaccumflask.png",
  [normalizeImageTitle("Copper Bottle")]: "/images/copperbottleset.png",
  [normalizeImageTitle("Steel Bottle")]: "/images/steelbottle.png",
  [normalizeImageTitle("Smart Temperature Bottle")]: "/images/sportsbottle1.png",
  [normalizeImageTitle("Travel Mug")]: "/images/flaskbottle.png",
  [normalizeImageTitle("Bamboo Bottle")]: "/images/sportsbottle.png",
  
  // Corporate Kits
  [normalizeImageTitle("Dealer Kits")]: "/images/dealerkit.png",
  [normalizeImageTitle("Distributor Kits")]: "/images/dealerkit.png",
  [normalizeImageTitle("Employee Welcome Kit")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Doctor Kits")]: "/images/doctorkit.png",
  [normalizeImageTitle("Architect Kits")]: "/images/architectkit1.png",
  [normalizeImageTitle("Contractor Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Mason Kits")]: "/kits/mason-kit.png",
  [normalizeImageTitle("Electrician Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Interior Designer Kits")]: "/images/architectkit1.png",
  [normalizeImageTitle("Pharma Representative Kits")]: "/images/doctorkit.png",
  [normalizeImageTitle("Hospital Staff Kits")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Startup Employee Onboarding Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Training & Seminar Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Joining Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Plumber Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Real Estate / Builder Kit")]: "/images/dealerkit.png",
  [normalizeImageTitle("Partner Kit")]: "/images/dealerkit.png",
  [normalizeImageTitle("Sales Team Kit")]: "/images/salesteamkit.png",
  [normalizeImageTitle("Sales Team Kits")]: "/images/salesteamkit.png",

  // Promotional Categories & Subcategories
  [normalizeImageTitle("Bags")]: LOCAL_IMAGE_POOLS.backpacks[0],
  [normalizeImageTitle("Backpacks")]: LOCAL_IMAGE_POOLS.backpacks[0],
  [normalizeImageTitle("Laptop Backpacks")]: LOCAL_IMAGE_POOLS.backpacks[1],
  [normalizeImageTitle("Travel Backpacks")]: LOCAL_IMAGE_POOLS.backpacks[2],
  [normalizeImageTitle("Laptop Bags")]: LOCAL_IMAGE_POOLS.laptopBags[0],
  [normalizeImageTitle("Travel Bags")]: LOCAL_IMAGE_POOLS.trolleyBags[1],
  [normalizeImageTitle("Duffle Bags")]: LOCAL_IMAGE_POOLS.duffleBags[0],
  [normalizeImageTitle("Trolley Bags")]: LOCAL_IMAGE_POOLS.trolleyBags[0],
  [normalizeImageTitle("Sling Bags")]: LOCAL_IMAGE_POOLS.slingBags[0],
  [normalizeImageTitle("Classic Sling Bags")]: LOCAL_IMAGE_POOLS.slingBags[0],
  [normalizeImageTitle("Premium Sling Bags")]: LOCAL_IMAGE_POOLS.slingBags[1],
  [normalizeImageTitle("Executive Sling Bags")]: LOCAL_IMAGE_POOLS.slingBags[2],
  [normalizeImageTitle("Eco Sling Bags")]: LOCAL_IMAGE_POOLS.slingBags[0],

  [normalizeImageTitle("Polo T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Round Neck T-Shirts")]: LOCAL_IMAGE_POOLS.roundNeckTshirts[0],

  [normalizeImageTitle("Promotional Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[0],
  [normalizeImageTitle("Sports Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[0],
  [normalizeImageTitle("Classic Sports Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[0],
  [normalizeImageTitle("Premium Sports Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[1],
  [normalizeImageTitle("Executive Sports Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[2],
  [normalizeImageTitle("Eco Sports Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[0],
  [normalizeImageTitle("Cotton Caps")]: LOCAL_IMAGE_POOLS.cottonCaps[0],
  [normalizeImageTitle("Classic Cotton Caps")]: LOCAL_IMAGE_POOLS.cottonCaps[0],
  [normalizeImageTitle("Premium Cotton Caps")]: LOCAL_IMAGE_POOLS.cottonCaps[1],
  [normalizeImageTitle("Executive Cotton Caps")]: LOCAL_IMAGE_POOLS.cottonCaps[2],
  [normalizeImageTitle("Eco Cotton Caps")]: LOCAL_IMAGE_POOLS.cottonCaps[3],
  [normalizeImageTitle("Caps")]: LOCAL_IMAGE_POOLS.sportsCaps[0],

  [normalizeImageTitle("Executive Diaries")]: LOCAL_IMAGE_POOLS.diaries[0],
  [normalizeImageTitle("Premium Diaries")]: LOCAL_IMAGE_POOLS.diaries[1],
  [normalizeImageTitle("Eco Notebooks")]: LOCAL_IMAGE_POOLS.diaries[2],
  [normalizeImageTitle("Standard Notebooks")]: LOCAL_IMAGE_POOLS.diaries[3],
  [normalizeImageTitle("Diaries")]: LOCAL_IMAGE_POOLS.diaries[0],
  [normalizeImageTitle("Diaries / Notebooks")]: LOCAL_IMAGE_POOLS.diaries[0],

  [normalizeImageTitle("Paper Weight")]: LOCAL_IMAGE_POOLS.paperWeight[0],
  [normalizeImageTitle("Table Mats")]: LOCAL_IMAGE_POOLS.tableMat[0],
  [normalizeImageTitle("Mouse Pad")]: LOCAL_IMAGE_POOLS.mousePad[0],
  [normalizeImageTitle("Desk Organiser")]: LOCAL_IMAGE_POOLS.deskOrganiser[0],
  [normalizeImageTitle("Desk Organizer")]: LOCAL_IMAGE_POOLS.deskOrganiser[0],
  [normalizeImageTitle("Table Top")]: "/images/tabletopup.png",

  [normalizeImageTitle("Festive Hampers")]: LOCAL_IMAGE_POOLS.festiveHampers[0],
  [normalizeImageTitle("Diwali Hampers")]: LOCAL_IMAGE_POOLS.diwaliHampers[0],
  [normalizeImageTitle("Holi Hampers")]: LOCAL_IMAGE_POOLS.holiHampers[0],
  [normalizeImageTitle("Eid Kits")]: LOCAL_IMAGE_POOLS.eidHampers[0],
  [normalizeImageTitle("Eid Hampers")]: LOCAL_IMAGE_POOLS.eidHampers[0],
  [normalizeImageTitle("Women's Day Gifts")]: LOCAL_IMAGE_POOLS.festiveHampers[1],
  [normalizeImageTitle("Christmas Kits")]: LOCAL_IMAGE_POOLS.festiveHampers[2],
  [normalizeImageTitle("New Year Gifts")]: LOCAL_IMAGE_POOLS.festiveHampers[0],
  [normalizeImageTitle("New Year Hampers")]: LOCAL_IMAGE_POOLS.festiveHampers[0],
  [normalizeImageTitle("Employee Welcome Hampers")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Welcome Hampers")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Diwali Premium Dry Fruit Hamper")]: LOCAL_IMAGE_POOLS.diwaliHampers[1],
  [normalizeImageTitle("Diwali Wellness Hamper")]: LOCAL_IMAGE_POOLS.diwaliHampers[2],
  [normalizeImageTitle("Holi Organic Color Hamper")]: LOCAL_IMAGE_POOLS.holiHampers[0],
  [normalizeImageTitle("Eid Gourmet Hamper")]: LOCAL_IMAGE_POOLS.eidHampers[1],
  [normalizeImageTitle("Women Day Appreciation Hamper")]: LOCAL_IMAGE_POOLS.festiveHampers[1],
  [normalizeImageTitle("Christmas Gourmet Hamper")]: LOCAL_IMAGE_POOLS.festiveHampers[2],
  [normalizeImageTitle("New Year Desk Hamper")]: LOCAL_IMAGE_POOLS.festiveHampers[0],
  [normalizeImageTitle("Client Thank You Hamper")]: "/images/clientthankyouhamper.png",
  [normalizeImageTitle("Employee Milestone Hamper")]: "/images/employeemilestonehamper.png",
  [normalizeImageTitle("Leadership Retreat Hamper")]: "/images/leadershipretreat.png",
};

export const localCatalogImage = (title: string) =>
  corporateKitImage(title) || LOCAL_CATALOG_IMAGES_BY_TITLE[normalizeImageTitle(title)];
