const normalizeImageTitle = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "");

const LOCAL_CATALOG_IMAGES_BY_TITLE: Record<string, string> = {
  [normalizeImageTitle("Executive Leather Desk Mat")]: "/images/leathermat.png",
  [normalizeImageTitle("Solid Wood Wireless Charging Dock")]: "/images/wirelesscharging.png",
  [normalizeImageTitle("Smart Temperature LED Sipper")]: "/images/smartsipper.png",
  [normalizeImageTitle("Premium Aluminum Laptop Stand")]: "/images/laptopstand.png",
  [normalizeImageTitle("Metal Rotating Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Wireless Charging Mousepad")]: "/images/mousepad.png",
  [normalizeImageTitle("Custom Tabletop Calendar")]: "/images/tabletopup.png",
  [normalizeImageTitle("Executive Acrylic Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Classic Acrylic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Eco Acrylic Keychain")]: "/images/ecoacrylickeychain.png",
  [normalizeImageTitle("Premium Acrylic Keychain")]: "/images/premiummetalkeychain.png",
  [normalizeImageTitle("Eco Backpack")]: "/images/ecopackback.png",
  [normalizeImageTitle("Architect Kits 1")]: "/images/architectkit1.png",
  [normalizeImageTitle("Architect Kits 2")]: "/images/architectkits2.png",
  [normalizeImageTitle("Architect Kits 3")]: "/images/architectkits3.png",
  [normalizeImageTitle("Architect Kits 4")]: "/images/architectkits4.png",
  [normalizeImageTitle("Architect Kits 5")]: "/images/architectkits5.png",
  [normalizeImageTitle("Contractor Kits 1")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Contractor Kits 2")]: "/images/contractorkits2.png",
  [normalizeImageTitle("Contractor Kits 3")]: "/images/contractorkits3.png",
  [normalizeImageTitle("Contractor Kits 4")]: "/images/contractorkits4.png",
  [normalizeImageTitle("Contractor Kits 5")]: "/images/contractorkits5.png",
  [normalizeImageTitle("Premium Corporate T-Shirt")]: "/images/polotshirt.png",
  [normalizeImageTitle("Classic Corporate T-Shirt")]: "/images/classictimelesspolotshirt.png",
  [normalizeImageTitle("Eco Corporate T-Shirt")]: "/images/tshirtgreen.png",
  [normalizeImageTitle("Executive Corporate T-Shirt")]: "/images/tshirtblue.png",

  // T-Shirts
  [normalizeImageTitle("T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Polo T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Round Neck T-Shirts")]: "/images/roundnecktshirt.png",
  [normalizeImageTitle("Crew Neck T-Shirts")]: "/images/roundnecktshirt.png",
  [normalizeImageTitle("Dry Fit T-Shirts")]: "/images/tshirtblue.png",
  [normalizeImageTitle("Event T-Shirts")]: "/images/tshirtyellow.png",
  [normalizeImageTitle("Polo T-Shirt")]: "/images/polotshirt.png",
  [normalizeImageTitle("Cotton Crew Neck")]: "/images/roundnecktshirt.png",
  [normalizeImageTitle("Corporate Dry Fit Tee")]: "/images/tshirtblue.png",
  [normalizeImageTitle("Premium Embroidered Tee")]: "/images/classictimelesspolotshirt.png",
  [normalizeImageTitle("Employee Event T-Shirt")]: "/images/tshirtyellow.png",
  [normalizeImageTitle("Printed Branding Tee")]: "/images/tshirtgreen.png",

  // Keychains
  [normalizeImageTitle("Keychains")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Metal Keychain")]: "/images/executivemetalkeychain.png",
  [normalizeImageTitle("Leather Keychain")]: "/images/leatherkeychain.png",
  [normalizeImageTitle("Acrylic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Plastic Keychain")]: "/images/plastickeychain.png",
  [normalizeImageTitle("Wooden Keychain")]: "/images/woodenkeychain.png",
  [normalizeImageTitle("Premium Metal Keychain")]: "/images/premiummetalkeychain.png",

  // Pens
  [normalizeImageTitle("Pens")]: "/images/pen1.png",
  [normalizeImageTitle("Premium Pens")]: "/images/pen1.png",
  [normalizeImageTitle("Eco Pens")]: "/images/pen2.png",
  [normalizeImageTitle("Gift Box Pens")]: "/images/pen3.png",
  [normalizeImageTitle("Engraved Pens")]: "/images/pen4.png",
  [normalizeImageTitle("Premium Pen Gift Set")]: "/images/pen5.png",
  [normalizeImageTitle("Parker Premium Pen")]: "/images/pen1.png",
  [normalizeImageTitle("Metal Roller Pen")]: "/images/pen2.png",
  [normalizeImageTitle("Bamboo Eco Pen")]: "/images/pen3.png",
  [normalizeImageTitle("Executive Signature Pen")]: "/images/pen4.png",
  [normalizeImageTitle("Stylus Pen")]: "/images/pen5.png",
  [normalizeImageTitle("Gift Box Pen Set")]: "/images/pen3.png",
  [normalizeImageTitle("Engraved Corporate Pen")]: "/images/pen4.png",
  [normalizeImageTitle("Premium Ball Pen")]: "/images/pen1.png",

  // Bottles & Drinkware
  [normalizeImageTitle("Drinkware")]: "/images/sportsbottle.png",
  [normalizeImageTitle("Flasks")]: "/images/flaskbottle.png",
  [normalizeImageTitle("Bottles")]: "/images/sportsbottle.png",
  [normalizeImageTitle("Vacuum Flask")]: "/images/premiumvaccumflask.png",
  [normalizeImageTitle("Copper Bottle")]: "/images/copperbottleset.png",
  [normalizeImageTitle("Steel Bottle")]: "/images/steelbottle.png",
  [normalizeImageTitle("Smart Temperature Bottle")]: "/images/sportsbottle1.png",
  [normalizeImageTitle("Travel Mug")]: "/images/flaskbottle.png",
  [normalizeImageTitle("Bamboo Bottle")]: "/images/sportsbottle.png",
  
  // Corporate Kits
  [normalizeImageTitle("Dealer Kits")]: "/images/dealerkit.png",
  [normalizeImageTitle("Distributor Kits")]: "/images/dealerkit.png",
  [normalizeImageTitle("Employee Welcome Kit")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Doctor Kits")]: "/images/doctorkit.png",
  [normalizeImageTitle("Architect Kits")]: "/images/architectkit1.png",
  [normalizeImageTitle("Contractor Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Mason Kits")]: "/kits/mason-kit.png",
  [normalizeImageTitle("Electrician Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Interior Designer Kits")]: "/images/architectkit1.png",
  [normalizeImageTitle("Pharma Representative Kits")]: "/images/doctorkit.png",
  [normalizeImageTitle("Hospital Staff Kits")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Startup Employee Onboarding Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Training & Seminar Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Joining Kits")]: "/images/joiningkit.png",
  [normalizeImageTitle("Plumber Kits")]: "/images/contractorkits1.png",
  [normalizeImageTitle("Real Estate / Builder Kit")]: "/images/dealerkit.png",
  [normalizeImageTitle("Partner Kit")]: "/images/dealerkit.png",
  [normalizeImageTitle("Sales Team Kit")]: "/images/salesteamkit.png",
  [normalizeImageTitle("Sales Team Kits")]: "/images/salesteamkit.png",

  // Promotional Categories & Subcategories
  [normalizeImageTitle("Bags")]: "/images/ecopackback.png",
  [normalizeImageTitle("Laptop Bags")]: "/images/ecopackback.png",
  [normalizeImageTitle("Travel Bags")]: "/images/ecopackback.png",
  [normalizeImageTitle("Duffle Bags")]: "/images/ecopackback.png",
  [normalizeImageTitle("Trolley Bags")]: "/images/ecopackback.png",
  [normalizeImageTitle("Sling Bags")]: "/images/ecopackback.png",

  [normalizeImageTitle("Polo T-Shirts")]: "/images/polotshirt.png",
  [normalizeImageTitle("Round Neck T-Shirts")]: "/images/roundnecktshirt.png",

  [normalizeImageTitle("Promotional Caps")]: "/images/keychain.png",
  [normalizeImageTitle("Sports Caps")]: "/images/keychain.png",
  [normalizeImageTitle("Cotton Caps")]: "/images/keychain.png",
  [normalizeImageTitle("Caps")]: "/images/keychain.png",

  [normalizeImageTitle("Executive Diaries")]: "/images/leathermat.png",
  [normalizeImageTitle("Premium Diaries")]: "/images/leathermat.png",
  [normalizeImageTitle("Eco Notebooks")]: "/images/leathermat.png",
  [normalizeImageTitle("Standard Notebooks")]: "/images/leathermat.png",
  [normalizeImageTitle("Diaries / Notebooks")]: "/images/leathermat.png",

  [normalizeImageTitle("Paper Weight")]: "/images/paperweight.png",
  [normalizeImageTitle("Table Mats")]: "/images/leathermat.png",
  [normalizeImageTitle("Mouse Pad")]: "/images/mousepad.png",
  [normalizeImageTitle("Desk Organiser")]: "/images/tabletopup.png",
  [normalizeImageTitle("Table Top")]: "/images/tabletopup.png",

  [normalizeImageTitle("Diwali Hampers")]: "/images/diwalihampers.png",
  [normalizeImageTitle("Holi Hampers")]: "/images/holihampers.png",
  [normalizeImageTitle("Eid Kits")]: "/images/eidkits.png",
  [normalizeImageTitle("Women's Day Gifts")]: "/images/womensdaykit.png",
  [normalizeImageTitle("Christmas Kits")]: "/images/christmaskit.png",
  [normalizeImageTitle("New Year Gifts")]: "/images/newyeargifts.png",
  [normalizeImageTitle("New Year Hampers")]: "/images/newyeargifts.png",
  [normalizeImageTitle("Employee Welcome Hampers")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Welcome Hampers")]: "/images/employeewelcome.png",
  [normalizeImageTitle("Diwali Premium Dry Fruit Hamper")]: "/images/premiumdryfruithamper.png",
  [normalizeImageTitle("Diwali Wellness Hamper")]: "/images/diwaliwellnesshamper.png",
  [normalizeImageTitle("Holi Organic Color Hamper")]: "/images/holiorganiccolorhamper.png",
  [normalizeImageTitle("Eid Gourmet Hamper")]: "/images/eidgourmenthamper.png",
  [normalizeImageTitle("Women Day Appreciation Hamper")]: "/images/womenappreciationhamper.png",
  [normalizeImageTitle("Christmas Gourmet Hamper")]: "/images/christmasgourmethamper.png",
  [normalizeImageTitle("New Year Desk Hamper")]: "/images/newyeardeskhamper.png",
  [normalizeImageTitle("Client Thank You Hamper")]: "/images/clientthankyouhamper.png",
  [normalizeImageTitle("Employee Milestone Hamper")]: "/images/employeemilestonehamper.png",
  [normalizeImageTitle("Leadership Retreat Hamper")]: "/images/leadershipretreat.png",
};

export const localCatalogImage = (title: string) => LOCAL_CATALOG_IMAGES_BY_TITLE[normalizeImageTitle(title)];
