export const mongoCollections = [
  "admins",
  "products",
  "categories",
  "subcategories",
  "brands",
  "orders",
  "quotes",
  "enquiries",
  "email_logs",
  "analytics",
  "settings",
] as const;

export const mongooseSchemaDefinitions = {
  admins: {
    name: "String, required",
    email: "String, required, unique, index",
    passwordHash: "String, required",
    role: "SUPER_ADMIN | ADMIN | EDITOR | VIEWER",
    active: "Boolean, default true",
    lastLogin: "Date",
    createdAt: "Date, index",
  },
  products: {
    name: "String, required",
    slug: "String, required, unique, index",
    description: "String",
    shortDescription: "String",
    categoryId: "ObjectId(categories), index",
    subCategoryId: "ObjectId(subcategories), index",
    brandId: "ObjectId(brands), index",
    featuredImage: "String",
    galleryImages: "String[]",
    features: "String[]",
    tags: "String[]",
    moq: "Number",
    status: "DRAFT | PUBLISHED | HIDDEN",
    createdAt: "Date, index",
    updatedAt: "Date",
  },
  categories: {
    name: "String, required",
    slug: "String, required, unique, index",
    description: "String",
    active: "Boolean",
    parentGroup: "String, index",
    createdAt: "Date, index",
  },
  subcategories: {
    name: "String, required",
    slug: "String, required, unique, index",
    category: "ObjectId(categories), index",
    parentGroup: "String, index",
    image: "String, required",
    active: "Boolean",
    createdAt: "Date, index",
  },
  brands: {
    name: "String, required",
    slug: "String, required, unique, index",
    logo: "String",
    active: "Boolean",
    createdAt: "Date, index",
  },
  orders: {
    customerName: "String, required",
    email: "String, required, index",
    phone: "String",
    company: "String",
    products: "String[]",
    total: "Number",
    status: "NEW | QUOTATION_SENT | CONFIRMED | PROCESSING | SHIPPED | DELIVERED | CANCELLED",
    createdAt: "Date, index",
    updatedAt: "Date",
  },
  quotes: {
    customerName: "String, required",
    email: "String, required, index",
    phone: "String, required",
    company: "String",
    city: "String",
    products: "String[]",
    quantity: "String",
    message: "String",
    status: "NEW | CONTACTED | QUOTATION_SENT | WON | LOST",
    createdAt: "Date, index",
    updatedAt: "Date",
  },
  enquiries: {
    name: "String, required",
    email: "String, required, index",
    phone: "String",
    company: "String",
    source: "String, index",
    message: "String",
    status: "NEW | READ | REPLIED | ARCHIVED",
    createdAt: "Date, index",
    updatedAt: "Date",
  },
  email_logs: {
    type: "String, required, index",
    recipient: "String, required, index",
    subject: "String, required",
    status: "QUEUED | SENT | FAILED | MOCKED",
    providerMessageId: "String",
    error: "String",
    createdAt: "Date, index",
  },
};
