export const PROMOTIONAL_CATEGORIES = [
  ["Pens", "pens", "Metal, executive, and plastic pens for corporate gifting."],
  ["T-Shirts", "t-shirts", "Promotional, corporate, and polo t-shirts."],
  ["Keychains", "keychains", "Metal, leather, and acrylic keychains."],
  ["Diaries / Notebooks", "diaries-notebooks", "Diaries, notebooks, and eco notebooks."],
  ["Caps", "caps", "Cotton and embroidered caps."],
  ["Paper Weights", "paper-weights", "Corporate paper weights."],
  ["Mouse Pads / Table Mats", "mouse-pads-table-mats", "Mouse pads and table mats."],
  ["Table Top Items", "table-top-items", "Desk organizers and pen stands."],
  ["Backpacks / Bags", "backpacks-bags", "Backpacks, laptop bags, and duffel bags."],
] as const;

export const PROMOTIONAL_SUBCATEGORIES = [
  ["Metal Pen", "metal-pen", "pens", "Metal pens for corporate giveaways."],
  ["Executive Pen", "executive-pen", "pens", "Executive pens for premium gifting."],
  ["Plastic Pen", "plastic-pen", "pens", "Plastic pens for bulk promotions."],
  ["Promotional T-Shirt", "promotional-tshirt", "t-shirts", "Promotional t-shirts for events and campaigns."],
  ["Corporate T-Shirt", "corporate-tshirt", "t-shirts", "Corporate t-shirts for teams and uniforms."],
  ["Polo T-Shirt", "polo-tshirt", "t-shirts", "Polo t-shirts for branded apparel programs."],
  ["Metal Keychain", "metal-keychain", "keychains", "Metal keychains for brand giveaways."],
  ["Leather Keychain", "leather-keychain", "keychains", "Leather keychains for premium gifting."],
  ["Acrylic Keychain", "acrylic-keychain", "keychains", "Acrylic keychains for promotional campaigns."],
  ["Executive Diary", "executive-diary", "diaries-notebooks", "Executive diaries for business gifting."],
  ["Custom Notebook", "custom-notebook", "diaries-notebooks", "Custom notebooks for branded stationery."],
  ["Eco Notebook", "eco-notebook", "diaries-notebooks", "Eco notebooks for sustainable gifting."],
  ["Cotton Caps", "cotton-caps", "caps", "Cotton caps for event and team use."],
  ["Embroidered Caps", "embroidered-caps", "caps", "Embroidered caps with logo branding."],
  ["Paper Weight", "paper-weight", "paper-weights", "Paper weights for desk gifting."],
  ["Mouse Pad", "mouse-pad", "mouse-pads-table-mats", "Branded mouse pads for office desks."],
  ["Table Mat", "table-mat", "mouse-pads-table-mats", "Table mats for office and executive desks."],
  ["Desk Organizer", "desk-organizer", "table-top-items", "Desk organizers for workspace gifting."],
  ["Pen Stand", "pen-stand", "table-top-items", "Pen stands for branded table top gifting."],
  ["Backpack", "backpack", "backpacks-bags", "Backpacks for corporate kits and events."],
  ["Laptop Bag", "laptop-bag", "backpacks-bags", "Laptop bags for professional gifting."],
  ["Duffel Bag", "duffel-bag", "backpacks-bags", "Duffel bags for travel and team gifting."],
] as const;

export const CORPORATE_KIT_SUBCATEGORIES = [
  ["Doctor Kits", "doctor-kits", "Medical-themed stationery, desk utilities, planners, and clinic-ready branded packs."],
  ["Architect Kits", "architect-kits", "Sketchbooks, design tools, swatches, rulers, and premium studio presentation kits."],
  ["Contractor Kits", "contractor-kits", "Field-ready branded bags, caps, notebooks, tools, and durable site essentials."],
  ["Mason Kits", "mason-kits", "Recognition and utility kits for masonry teams with workwear, drinkware, and field packaging."],
  ["Electrician Kits", "electrician-kits", "Safety and utility kits with gloves, testers, notebooks, caps, and branded field packs."],
  ["Interior Designer Kits", "interior-designer-kits", "Designer sample kits with swatches, notebooks, rulers, pens, and presentation boxes."],
  ["Pharma Representative Kits", "pharma-representative-kits", "Representative kits with folders, sample inserts, planners, and branded cartons."],
  ["Hospital Staff Kits", "hospital-staff-kits", "Hospital staff appreciation kits with bottles, badge reels, notebooks, and care cards."],
  ["Startup Employee Onboarding Kits", "startup-employee-onboarding-kits", "Startup culture kits with tees, stickers, tumblers, notebooks, and tech organizers."],
  ["Training & Seminar Kits", "training-seminar-kits", "Delegate kits with notebooks, pens, agendas, badges, bottles, and certificates."],
  ["Joining Kits", "joining-kits", "Employee onboarding kits with diary, pen, sipper, welcome card, and branded box."],
  ["Dealer Kits", "dealer-kits", "Dealer launch kits with sales collateral, partner folders, and channel welcome packs."],
  ["Distributor Kits", "distributor-kits", "Distributor growth kits with travel utilities, trophies, and campaign literature."],
  ["Plumber Kits", "plumber-kits", "Functional kits with branded toolbags, notebooks, drinkware, and trade accessories."],
  ["Real Estate / Builder Kit", "real-estate-builder-kit", "Builder and handover kits with folders, keys, desk gifts, and luxury packaging."],
  ["Education / School Kit", "education-school-kit", "School and education kits with notebooks, bottles, bags, stationery, and ID accessories."],
  ["Partner Kit", "partner-kit", "Partner appreciation kits with premium treats, awards, desk gifts, and thank-you cards."],
  ["Sales Team Kit", "sales-team-kit", "Sales starter kits with polos, backpacks, bottles, planners, and pitch material."],
] as const;

export const HAMPER_SUBCATEGORIES = [
  ["Diwali Hampers", "diwali-hampers", "Diwali dry fruit, wellness, diya, and festive premium corporate hampers."],
  ["Holi Hampers", "holi-hampers", "Holi hampers with organic colors, snacks, thandai mixes, and colorful branded boxes."],
  ["Eid Kits", "eid-kits", "Eid gourmet hampers with dates, nuts, sweets, and elegant themed presentation."],
  ["Women's Day Gifts", "womens-day-gifts", "Women's Day appreciation hampers with self-care, candles, chocolates, and cards."],
  ["Christmas Kits", "christmas-kits", "Christmas gourmet hampers with cookies, cocoa, candles, ornaments, and winter sleeves."],
  ["New Year Hampers", "new-year-hampers", "New Year desk hampers with planners, calendars, tumblers, and premium treats."],
] as const;

export const BRAND_PARTNERS = [
  ["Adidas", "adidas", "Apparel & Lifestyle", "Sportswear"],
  ["Reebok", "reebok", "Apparel & Lifestyle", "Sportswear"],
  ["Rare Rabbit", "rare-rabbit", "Apparel & Lifestyle", "Premium Apparel"],
  ["Parker", "parker", "Premium Writing Instruments", "Executive Stationery"],
  ["Beardo", "beardo", "Grooming & Lifestyle", "Personal Care"],
  ["Cello", "cello", "Writing & Drinkware", "Stationery & Utility"],
  ["Mokobara", "mokobara", "Travel & Luggage", "Premium Travel"],
  ["VIP", "vip", "Travel & Luggage", "Luggage"],
  ["JBL", "jbl", "Audio & Electronics", "Audio"],
  ["U-bon", "u-bon", "Audio & Electronics", "Audio"],
  ["Borosil", "borosil", "Drinkware & Kitchenware", "Glassware"],
  ["Wildcraft", "wildcraft", "Travel & Outdoor", "Bags & Gear"],
  ["Welspun", "welspun", "Home & Lifestyle", "Home Utility"],
  ["Blue Pond", "blue-pond", "Drinkware & Utility", "Corporate Utility"],
  ["Boat", "boat", "Audio & Electronics", "Audio"],
  ["Philips", "philips", "Electronics & Appliances", "Electronics"],
  ["Aiwa", "aiwa", "Audio & Electronics", "Audio"],
] as const;

export const BRAND_LOGO_PATHS: Record<string, string> = {
  adidas: "/logos/adidas.jpg",
  reebok: "/logos/reebok.png",
  "rare-rabbit": "/logos/rarerabit.png",
  parker: "/logos/parker.png",
  beardo: "/logos/beardo.png",
  cello: "/logos/cello.png",
  mokobara: "/logos/mokobara.png",
  vip: "/logos/vip.webp",
  jbl: "/logos/jbl.png",
  "u-bon": "/logos/ubon.webp",
  borosil: "/logos/borosil.png",
  wildcraft: "/logos/wildcraft.png",
  welspun: "/logos/welspun.png",
  "blue-pond": "/logos/bluepond.png",
  boat: "/logos/boat.png",
  philips: "/logos/philips.png",
  aiwa: "/logos/aiwa.png",
};
